### ISSUE TITLE
Remaining RMG-Cat issues identified at hackathon

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1590]
I'm placing all of the unresolved issues which were identified during the hackathon here for now. Items can be moved to separate issues if the need arises.

- [ ] Filter reactions for `SurfaceReactor` not implemented
- [ ] Pressure not integrated for in `SurfaceReactor`
- [ ] Jacobian/sensitivity analysis not implemented in `SurfaceReactor`
- [ ] Unit tests needed for `SurfaceRateCoefficient` in `rmgpy/quantity.py`
- [ ] Hard coding in `family.py` checks for `'adsorption'` in family name
- [ ] Update images for kinetics families
- [ ] Creation of gas phase molecule from surface molecule in thermo.py could (should?) be made a molecule method, with appropriate unit tests

Topics with existing issues:
- [ ] Missing sigma terms for bidentate species - cfgoldsmith/RMG-Py#4
- [ ] X in vdW typed as Xv - cfgoldsmith/RMG-Py#58
- [ ] Checking collision limit causes issues - cfgoldsmith/RMG-Py#61
- [ ] Ranged reactors don't work - cfgoldsmith/RMG-Py#73
- [ ] DeltaAtomicAdsorptionEnergies hard to set - cfgoldsmith/RMG-Py#76
