### ISSUE TITLE
Python 3 finalization tasks

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1726]
Once #1724 is merged, the bulk of the Python 3 transition will be completed. However, there are final testing and clean up tasks which will still need to be done. The purpose of this issue is to keep track of these tasks and make sure that they are done before releasing RMG 3.0.

To do:
- [x] Remove all `__future__` imports #1730 
- [x] Update all IPython notebooks #1735
- [ ] Update RMG-database scripts and notebooks https://github.com/ReactionMechanismGenerator/RMG-database/pull/364
- [x] Remove dde models from RMG-database ReactionMechanismGenerator/RMG-database#358
- [x] Update documentation as needed @hwpang  (particularly regarding installation @mliu49  and @amarkpayne ) #1767
- [ ] Update global uncertainty analysis (transition to MUQ 2) #1738 

Testing:
- [x] Run a pdep job @alongd
- [x] Run a job with ml thermo @yunsiechung 
- [ ] Run a job with QMTP @agnes (debug conformer issue @dranasinghe and @alongd )
- [x] Run a catalysis job @maforsuelo 
- [x] Run a parallel job - natural gas combustion case for 3d 20h no error but see for warning messages below
- [x] Run a liquid job @hwpang 
- [x] Run a large pdep network in Arkane @alongd
- [x] Run an isotopes job @goldmanm 
- [x] Run sensitivity and local uncertainty analysis @oscarwumit 
- [x] Test all scripts @yunsiechung 
- [x] Test all IPython notebooks

Note that some of jobs are run by RMG-tests, but the point here is to run a longer job and ideally a case that is important to you.

Please comment (or edit) if you have suggestions for other items to add to either list.

**Comment by ajocher** [comment]
Running the examples/rmg/1,3-hexadiene case without pdep: after 6:52 min run time this error happens

  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmg.py", line 107, in <module>
    main()
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmg.py", line 101, in main
    rmg.execute(**kwargs)
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/rmg/main.py", line 651, in execute
    self.initialize(**kwargs)
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/rmg/main.py", line 486, in initialize
    self.load_database()
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/rmg/main.py", line 410, in load_database
    family.add_rules_from_training(thermo_database=self.database.thermo)
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/data/kinetics/family.py", line 1231, in add_rules_from_training
    reactant.thermo = thermo_database.get_thermo_data(reactant, training_set=True)
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/data/thermo.py", line 1244, in get_thermo_data
    tdata = self.estimate_radical_thermo_via_hbi(molecule, quantum_mechanics.get_thermo_data)
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/data/thermo.py", line 1841, in estimate_radical_thermo_via_hbi
    thermo_data_sat = stable_thermo_estimator(saturated_struct)
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/qm/main.py", line 217, in get_thermo_data
    thermo0 = qm_molecule_calculator.generate_thermo_data()
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/qm/molecule.py", line 362, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/qm/mopac.py", line 303, in generate_qm_data
    self.create_geometry()
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/qm/molecule.py", line 328, in create_geometry
    self.geometry.generate_rdkit_geometries()
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/qm/molecule.py", line 138, in generate_rdkit_geometries
    self.save_coordinates_from_rdmol(rdmol, min_e_id, rdatom_idx)
  File "/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/qm/molecule.py", line 176, in save_coordinates_from_rdmol
    point = rdmol.GetConformer(min_e_id).GetAtomPosition(atom.sorting_label)
ValueError: Bad Conformer Id

**Comment by mliu49** [comment]
Could you double-check this example on v2.4.1? I got the error on both master and the v2.5.0 branch.

Initial investigation suggests issues with RDKit conformer generation. The molecule this breaks on is `C1=C2CCC(C1)C2`, and RDKit fails to generate any conformers for it for some reason.

**Comment by ajocher** [comment]
RMG v2.4.1 fails with the same error. 
The current git HEAD for RMG-Py is:
        af0ef48bda472c4689605015ac0adda102425aae
        Tue Jul 23 14:48:04 2019 -0400
The current git HEAD for RMG-database is:
        d52ebabb3478377660dd4c25c938844549d9ec42
        Thu Jul 18 10:30:25 2019 -0400

RMG v2.4.0 fails with the same error using the v2.4.1 rmg_env but works with v2.4.0 rmg_env
The current git HEAD for RMG-Py is:
        caebd4895dfaee296b6562b28f89e6c350422cca
        Fri Jun 14 18:30:27 2019 -0400
The current git HEAD for RMG-database is:
        08b8214e8b4c869411f498cb50acb76b012520b4
        Fri Jun 14 18:15:05 2019 -0400 

The v2.4.1 environment requests "-rdkit >=2018" while the v2.4.0 environment uses rdkitVersion '2016.03.4'. Not sure what good fix would be.

**Comment by ajocher** [comment]
While running the parallel case the following warning messages were printed 

/home/ajocher/codes/RMG/miniconda3/envs/rmg_env/lib/python3.7/site-packages/scipy/optimize/optimize.py:1826: LinAlgWarning: Ill-conditioned matrix (rcond=9.79183e-18): result may not be accurate.
  fu = func(x, *args)
/home/ajocher/codes/RMG/miniconda3/envs/rmg_env/lib/python3.7/site-packages/scipy/optimize/optimize.py:1826: LinAlgWarning: Ill-conditioned matrix (rcond=5.9437e-17): result may not be accurate.
  fu = func(x, *args)
/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/rmg/main.py:793: RuntimeWarning: invalid value encountered in true_divide
  conditions=self.rmg_memories[index].get_cond()
/home/ajocher/codes/RMG/RMG3/RMG-Py/rmgpy/rmg/main.py:793: RuntimeWarning: divide by zero encountered in true_divide
  conditions=self.rmg_memories[index].get_cond()
/home/ajocher/codes/RMG/miniconda3/envs/rmg_env/lib/python3.7/site-packages/scipy/optimize/optimize.py:1826: LinAlgWarning: Ill-conditioned matrix (rcond=5.11164e-17): result may not be accurate.
  fu = func(x, *args)

**Comment by yunsiechung** [comment]
Arkane does not generate `conformer` and `thermo` any longer in `output.py` for thermo job.

Running `examples/arkane/species/Benzyl/input.py` will produce the `output.py` that is missing `conformer` and `thermo`

**Comment by yunsiechung** [comment]
I checked ml thermo by:
- running rmg minimal_ml example and checking that the thermo of the species that passed the ml estimating criteria was estimated from ml
- making sure the unittests for ml thermo are still there and they all passed.

Ml thermo looks fine.
